#! /bin/bash

# Rémi Attab (remi.attab@gmail.com), 12 Apr 2014
# FreeBSD-style copyright and disclaimer apply

# Small utility to run compile performance tests.


TEST_NAME=$1_test

nice make -kj8 reflect \
    && touch tests/cperf/$TEST_NAME.cpp \
    && time make cperf_$TEST_NAME
